---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: limits-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:limits-enforced:default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: limits-enforced
  name: reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "configmaps", "deployments"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader
  namespace: limits-enforced
subjects:
- kind: User
  name: system:serviceaccount:limits-enforced:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
