apiVersion: v1
kind: ConfigMap
metadata:
  name: limits-initializer
data:
  config: |
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
